FROM node:24.15.0-alpine AS build
WORKDIR /app
COPY frontend/package*.json ./
RUN npm ci
COPY frontend/ ./
RUN npm run build

FROM nginxinc/nginx-unprivileged:1.28-alpine
COPY infraestructura/nginx/default.conf /etc/nginx/conf.d/default.conf
COPY --from=build /app/dist/tutoria/browser /usr/share/nginx/html
EXPOSE 8080
